attention_probs_dropout_prob: 0.1
bos_token_id: 0
compute_type: mstype.float32
dtype: mstype.float32
eos_token_id: 2
hidden_act: "gelu"
hidden_dropout_prob: 0.1
hidden_size: 768
initializer_range: 0.02
intermediate_size: 3072
max_position_embeddings: 514
num_attention_heads: 12
num_hidden_layers: 12
pad_token_id: 1
seq_length: 128
type_vocab_size: 1
use_relative_positions: False
vocab_size: 50265
