# Builtin Configurations

model_name: "fasttext"
device_target: "GPU"

PREPROCESS:
  max_len: 467
  mid_dir_path: "./temp_data"

MODEL_PARAMETERS:
  vocab_size: 1383812
  embedding_dims: 16
  num_class: 4

OPTIMIZER:
  function: "Adam"
  lr: 0.2
  min_lr: 0.000001
  decay_steps: 236
  warmup_steps: 400000
  poly_lr_scheduler_power: 0.001

TRAIN:
  data_path: "/root/fasttext/ag_news_csv/train.csv"
  batch_size: 512
  buckets: [64, 128, 467]
  epochs: 5
  epoch_count: 1
  loss_function: "SoftmaxCrossEntropyWithLogits"
  pretrain_ckpt_dir: ""
  save_ckpt_steps: 116
  save_ckpt_dir: "./ckpt"
  keep_ckpt_max: 10
  run_distribute: False
  distribute_batch_size_gpu: 64

VALID:
  data_path: "/root/fasttext/ag_news_csv/test.csv"
  batch_size: 512
  model_ckpt: "/root/HongYeTest/mindtext/mindtext/classification/tools/ckpt/fasttext-5_236.ckpt"
  buckets: [467]

INFER:
  data_path: "/root/fasttext/ag_news_csv/test.csv"
  batch_size: 512
  model_ckpt: ""
  buckets: [467]

EXPORT:
  device_id: 0
  ckpt_file: "/root/HongYeTest/mindtext/mindtext/classification/tools/ckpt/fasttext-5_236.ckpt"
  file_name: "fasttext"
  file_format: "AIR"
