context:
    mode: 0 #0--静态图模式; 1--动态图模式
    device_target: "GPU"

train:
    dataset:
        type: CONLLDataset #Dataset类型
        paths: './examples/lstm_cnn/conll2003' #数据集路径，需要指定
        batch_size: 512
        columns_list: ['input_ids', 'input_mask', 'ner_tags']
        test_columns_list: ['input_ids', 'input_mask', 'ner_tags']

eval:
    dataset:
        type: CONLLDataset #Dataset类型
        paths: './examples/lstm_cnn/conll2003' #数据集路径，需要指定
        batch_size: 512
        columns_list: ['input_ids', 'input_mask', 'ner_tags', 'input_length']
        test_columns_list: ['input_ids', 'input_mask', 'ner_tags', 'input_length']

model:
    save_path: './examples/lstm_cnn/lstm_cnn_model/model.ckpt' #模型保存路径
    result_path: './examples/lstm_cnn/result' #评估结果目录

epochs: 85
