context:
    mode: 0 #0--静态图模式; 1--动态图模式
    device_target: "GPU"

dataset:
    type: XSUMDataset #Dataset类型
    paths: '' #数据集路径，需要指定
    batch_size: 11
    test_batch_size: 30
    tokenizer: 'bart-large-xsum' #分词器路径
    max_length: 768
    max_pair_length: 60
    stream: True
    truncation_strategy: True
    columns_list: ["input_ids", "attention_mask", "labels"]
    test_columns_list: ["input_ids", "attention_mask"]

model:
    config_path: './config/model_config.json'
    ckpt_path: '' #初始化权重路径，需要指定
    save_path: './ckpt/xsum/ft.ckpt' #模型保存路径
    result_path: './result/xsum' #评估结果目录
    beam_width: 2

epochs: 4