context:
    mode: 0 #0--静态图模式; 1--动态图模式
    device_target: "GPU"

dataset:
    type: SQuAD1.1 #Dataset类型
    path: './dataset/' #数据集路径，需要指定
    wiki_entity_path: './dataset/wiki_entity/'  # wiki_entity file
    entity_vocab_path: "./dataset/vocab_entity.jsonl"
    SQUAD_TRAIN_MR: "dataset/train_features.mindrecord"
    SQUAD_DEV_MR: "dataset/dev_features.mindrecord"
    batch_size: 2
    eval_batch_size: 32
    tokenizer: "studio-ousia/luke-large" #分词器
    max_length: 512
    columns_list: ['word_ids',  'word_segment_ids', 'word_attention_mask',
               'entity_ids', 'entity_position_ids', 'entity_segment_ids',
               'entity_attention_mask', 'start_positions', 'end_positions']
    test_columns_list: ['unique_id', 'word_ids',  'word_segment_ids', 'word_attention_mask',
               'entity_ids', 'entity_position_ids', 'entity_segment_ids',
               'entity_attention_mask']

model:
    config_path: 'config/luke_squad.yaml'
    ckpt_path: 'ckpt/luke-large.ckpt' #初始化权重路径，需要指定
    save_path: 'ckpt/luke-qa.ckpt' #模型保存路径
    result_path: 'result/' #评估结果目录

epoch: 1

